#
# Wave v2.0
#

# Add the permission nodes you DON'T want players to have
# TotalFreedomMod is required for the plugin to work
# More information at: https://github.com/TFPatches/TotalFreedomMod

operator:
  permissions:
  - essentials.antioch
  - essentials.backup
  - essentials.ban
  - essentials.banip
  - essentials.broadcast
  - essentials.broadcastworld
  - essentials.burn
  - essentials.chat.ignoreexempt
  - essentials.chat.spy.exempt
  - essentials.clearinventory.all
  - essentials.clearinventory.multiple
  - essentials.createkit
  - essentials.essentials
  - essentials.fireball
  - essentials.fly.others
  - essentials.gamemode
  - essentials.helpop
  - essentials.ignore
  - essentials.kick
  - essentials.kickall
  - essentials.kill
  - essentials.msg.multiple
  - essentials.mute
  - essentials.nuke
  - essentials.powertool
  - essentials.powertooltoggle
  - essentials.ptime.others
  - essentials.pweather.others
  - essentials.seen.ip
  - essentials.setjail
  - essentials.spawn.others
  - essentials.speed.others
  - essentials.sudo
  - essentials.tempban
  - essentials.thunder
  - essentials.tpaall
  - essentials.tpall
  - essentials.tpoffline
  - essentials.tptoggle.others
  - essentials.unban
  - essentials.unbanip
  - essentials.vanish
  - essentials.vanish.others
  - essentials.warp.others
  - essentials.weather
  - essentials.whois.ip
  - libsdisguises.disguise.area_affect_cloud
  - libsdisguises.disguise.dropped_item
  - libsdisguises.disguise.ender_crystal
  - libsdisguises.disguise.ender_dragon
  - libsdisguises.disguise.ghast
  - libsdisguises.disguise.giant
  - libsdisguises.disguise.item_frame
  - libsdisguises.disguise.player
  - libsdisguises.disguise.wither
  - libsdisguises.disguiseentity.area_affect_cloud
  - libsdisguises.disguiseentity.dropped_item
  - libsdisguises.disguiseentity.ender_crystal
  - libsdisguises.disguiseentity.ender_dragon
  - libsdisguises.disguiseentity.ghast
  - libsdisguises.disguiseentity.giant
  - libsdisguises.disguiseentity.item_frame
  - libsdisguises.disguiseentity.magma_cube
  - libsdisguises.disguiseentity.player
  - libsdisguises.disguiseentity.slime
  - libsdisguises.disguiseentity.wither
  - libsdisguises.disguiseplayer.*
  - libsdisguises.disguiseradius.area_affect_cloud
  - libsdisguises.disguiseradius.dropped_item
  - libsdisguises.disguiseradius.ender_crystal
  - libsdisguises.disguiseradius.ender_dragon
  - libsdisguises.disguiseradius.ghast
  - libsdisguises.disguiseradius.giant
  - libsdisguises.disguiseradius.item_frame
  - libsdisguises.disguiseradius.magma_cube
  - libsdisguises.disguiseradius.player
  - libsdisguises.disguiseradius.slime
  - libsdisguises.disguiseradius.wither
  - libsdisguises.reload
  - libsdisguises.undisguiseplayer
  - voxelsniper.brush.entity
  - voxelsniper.brush.removentity
  - wave.reload
  - wave.reloadpermissions
superadmin:
  permissions:
  - essentials.antioch
  - essentials.backup
  - essentials.ban
  - essentials.banip
  - essentials.broadcast
  - essentials.broadcastworld
  - essentials.burn
  - essentials.createkit
  - essentials.essentials
  - essentials.fireball
  - essentials.helpop
  - essentials.ignore
  - essentials.kickall
  - essentials.kill
  - essentials.mute
  - essentials.nuke
  - essentials.powertool
  - essentials.powertooltoggle
  - essentials.setjail
  - essentials.sudo
  - essentials.tempban
  - essentials.thunder
  - essentials.tpaall
  - essentials.unban
  - essentials.unbanip
  - essentials.weather
  - libsdisguises.disguise.area_affect_cloud
  - libsdisguises.disguise.dropped_item
  - libsdisguises.disguise.ender_crystal
  - libsdisguises.disguise.ender_dragon
  - libsdisguises.disguise.ghast
  - libsdisguises.disguise.giant
  - libsdisguises.disguise.item_frame
  - libsdisguises.disguise.magma_cube
  - libsdisguises.disguise.player
  - libsdisguises.disguise.slime
  - libsdisguises.disguise.wither
  - libsdisguises.disguiseentity.area_affect_cloud
  - libsdisguises.disguiseentity.dropped_item
  - libsdisguises.disguiseentity.ender_crystal
  - libsdisguises.disguiseentity.ender_dragon
  - libsdisguises.disguiseentity.ghast
  - libsdisguises.disguiseentity.giant
  - libsdisguises.disguiseentity.item_frame
  - libsdisguises.disguiseentity.magma_cube
  - libsdisguises.disguiseentity.player
  - libsdisguises.disguiseentity.slime
  - libsdisguises.disguiseentity.wither
  - libsdisguises.disguiseplayer.*
  - libsdisguises.disguiseradius.area_affect_cloud
  - libsdisguises.disguiseradius.dropped_item
  - libsdisguises.disguiseradius.ender_crystal
  - libsdisguises.disguiseradius.ender_dragon
  - libsdisguises.disguiseradius.ghast
  - libsdisguises.disguiseradius.giant
  - libsdisguises.disguiseradius.item_frame
  - libsdisguises.disguiseradius.magma_cube
  - libsdisguises.disguiseradius.player
  - libsdisguises.disguiseradius.slime
  - libsdisguises.disguiseradius.wither
  - libsdisguises.undisguiseplayer