name: ${project.name}
version: ${project.version}
description: A permission plugin designed to work with TotalFreedomMod
author: Model_3
main: me.telesphoreo.wave.Wave
depend: [TotalFreedomMod]
api-version: 1.13
commands:
  wave:
    usage: /<command> [reload]
    description: Shows information about or reload Wave
  reloadpermissions:
    usage: /<command> <<player> | -a>
    description: Reload permissions for everyone or a player
    aliases: [rp,reloadperms]